---  
- name: Pull default container image
  community.docker.docker_image:
    name: "{{ default_container_image }}"
    source: pull

- name: Create {{ primary_container_count }} primary node container
  community.docker.docker_container:
    name: "{{ default_container_name }}{{ primary_container_count }}"
    image: "{{ default_container_image}}"
    command: "{{ default_container_command }}"
    state: present
    #with_sequence: count={{ primary_container_count }}
