---
- name: Pull default container image
  community.docker.docker_image:
    name: "{{ default_container_image }}"
    source: pull

- name: Create {{secondary_container_count}} secondary node containers
  community.docker.docker_container:
    name: "{{ default_container_name }}{{ item }}"
    image: "{{ default_container_image}}"
    command: "{{ default_container_command }}"
    state: present
  with_sequence: count={{ secondary_container_count }}
